name: Twitch Clips to Discord

on:
  schedule:
    - cron: "05 18 * * *" # Every day at 15:00 GMT+1
  workflow_dispatch:
  
jobs:
  send_clips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download clips_sent.json artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: clips_sent
          path: ./data/clips_sent.json
        continue-on-error: true # Ignore the error if the artifact does not exist yet

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py

      - name: Upload clips_sent.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: clips_sent
          path: ./data/clips_sent.json
